#!/usr/bin/env python3
"""Convert the v0.x 8SVX sounds (data/sound*.iff) into src/sfx_data.c.

The Amiga side copies them to chip RAM (sfxOpen) and plays them raw: no IFF
parsing, no file loading. (Not __chip: the hunk flag got lost in the build.)
Samples above Paula's ~28 kHz DMA limit (sound1/2 are 48 kHz) are halved
(2-sample average) so they play at the pitch they were made for.
    tools/iff2c.py            # rewrite src/sfx_data.c
"""
import os
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAL_CLOCK = 3546895
MAX_RATE = 28000


def read_8svx(path):
    d = open(path, "rb").read()
    assert d[:4] == b"FORM" and d[8:12] == b"8SVX", path
    rate, body, p = None, None, 12
    while p < len(d):
        cid, n = d[p:p + 4], struct.unpack(">I", d[p + 4:p + 8])[0]
        if cid == b"VHDR":
            rate = struct.unpack(">H", d[p + 20:p + 22])[0]
        elif cid == b"BODY":
            body = d[p + 8:p + 8 + n]
        p += 8 + n + (n & 1)
    if rate is None or body is None:
        raise SystemExit(f"{path}: no VHDR or BODY chunk")
    return rate, body


def halve(body):
    s = [b - 256 if b > 127 else b for b in body]
    out = [(s[i] + s[i + 1]) // 2 for i in range(0, len(s) - 1, 2)]
    return bytes(v & 0xFF for v in out)


def main():
    out = ["// Generated by tools/iff2c.py from data/sound*.iff - do not edit.",
           '#include "sfx.h"', ""]
    table = []
    for i in range(4):
        rate, body = read_8svx(os.path.join(ROOT, "data", f"sound{i}.iff"))
        while rate > MAX_RATE:
            body, rate = halve(body), rate // 2
        if len(body) & 1:
            body += b"\0"
        rows = [", ".join(f"0x{b:02x}" for b in body[j:j + 16]) for j in range(0, len(body), 16)]
        out.append(f"static const UBYTE s_sfx{i}[{len(body)}] __attribute__((aligned(2))) = {{")
        out += [f"\t{r}," for r in rows]
        out += ["};", ""]
        table.append(f"\t{{s_sfx{i}, {len(body) // 2}, {round(PAL_CLOCK / rate)}}},  // {rate} Hz")
    out.append("const tSfxSample g_pSfx[SFX_COUNT] = {")
    out += table
    out.append("};")
    with open(os.path.join(ROOT, "src", "sfx_data.c"), "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
